// package pokemanz;
import java.util.*;

/*
 * This class models a completed, though basic, Pokedex. It contains a set that maps
 * each species of Pokemon with their Pokedex number.
 */

public class Dex{
    HashMap a = new HashMap(152);
    HashMap b = new HashMap(152);
    
    Dex(int dex){
		if (dex == 0){
			//create dex a, listed by name
			this.a.put("Honey Badger",0);
			this.a.put("Bulbasaur",1);
			this.a.put("Ivysaur", 2);
			this.a.put("Venusaur", 3);
			this.a.put("Charmander", 4);
			this.a.put("Charmeleon", 5);
			this.a.put("Charizard", 6);
			this.a.put("Squirtle", 7);
			this.a.put("Wartortle", 8);
			this.a.put("Blastoise", 9);
			this.a.put("Caterpie", 10);
			this.a.put("Metapod", 11);
			this.a.put("Butterfree", 12);
			this.a.put("Weedle", 13);
			this.a.put("Kakuna", 14);
			this.a.put("Beedrill", 15);
			this.a.put("Pidgey", 16);
			this.a.put("Pidgeotto", 17);
			this.a.put("Pidgeot", 18);
			this.a.put("Rattata", 19);
			this.a.put("Raticate", 20);
			this.a.put("Spearow", 21);
			this.a.put("Fearow", 22);
			this.a.put("Ekans", 23);
			this.a.put("Arbok", 24);
			this.a.put("Pikachu", 25);
			this.a.put("Raichu", 26);
			this.a.put("Sandshrew", 27);
			this.a.put("Sandslash", 28);
			this.a.put("Nidoran (Female)", 29);
			this.a.put("Nidorina", 30);
			this.a.put("Nidoqueen", 31);
			this.a.put("Nidoran (Male)", 32);
			this.a.put("Nidorino", 33);
			this.a.put("Nidoking", 34);
			this.a.put("Clefairy", 35);
			this.a.put("Clefable", 36);
			this.a.put("Vulpix", 37);
			this.a.put("Ninetales", 38);
			this.a.put("Jigglypuff", 39);
			this.a.put("Wigglytuff", 40);
			this.a.put("Zubat", 41);
			this.a.put("Golbat", 42);
			this.a.put("Oddish", 43);
			this.a.put("Gloom", 44);
			this.a.put("Vileplume", 45);
			this.a.put("Paras", 46);
			this.a.put("Parasect", 47);
			this.a.put("Venonat", 48);
			this.a.put("Venomoth", 49);
			this.a.put("Diglett", 50);
			this.a.put("Dugtrio", 51);
			this.a.put("Meowth", 52);
			this.a.put("Persian", 53);
			this.a.put("Psyduck", 54);
			this.a.put("Golduck", 55);
			this.a.put("Mankey", 56);
			this.a.put("Primeape", 57);
			this.a.put("Growlithe", 58);
			this.a.put("Arcanine", 59);
			this.a.put("Poliwag", 60);
			this.a.put("Poliwhirl", 61);
			this.a.put("Poliwrath", 62);
			this.a.put("Abra", 63);
			this.a.put("Kadabra", 64);
			this.a.put("Alakazam", 65);
			this.a.put("Machop", 66);
			this.a.put("Machoke", 67);
			this.a.put("Machamp", 68);
			this.a.put("Bellsprout", 69);
			this.a.put("Weepinbell", 70);
			this.a.put("Victreebell", 71);
			this.a.put("Tentacool", 72);
			this.a.put("Tentacruel", 73);
			this.a.put("Geodude", 74);
			this.a.put("Graveler", 75);
			this.a.put("Golem", 76);
			this.a.put("Ponyta", 77);
			this.a.put("Rapidash", 78);
			this.a.put("Slowpoke", 79);
			this.a.put("Slowbro", 80);
			this.a.put("Magnemite", 81);
			this.a.put("Magneton", 82);
			this.a.put("Farfetch'd", 83);
			this.a.put("Doduo", 84);
			this.a.put("Dodrio", 85);
			this.a.put("Seel", 86);
			this.a.put("Dewgong", 87);
			this.a.put("Grimer", 88);
			this.a.put("Muk", 89);
			this.a.put("Shellder", 90);
			this.a.put("Cloyster", 91);
			this.a.put("Ghastly", 92);
			this.a.put("Haunter", 93);
			this.a.put("Gengar", 94);
			this.a.put("Onix", 95);
			this.a.put("Drowzee", 96);
			this.a.put("Hypno", 97);
			this.a.put("Krabby", 98);
			this.a.put("Kingler", 99);
			this.a.put("Voltorb", 100);
			this.a.put("Electrode", 101);
			this.a.put("Exeggcute", 102);
			this.a.put("Exeggcutor", 103);
			this.a.put("Cubone", 104);
			this.a.put("Marowak", 105);
			this.a.put("Hitmonlee", 106);
			this.a.put("Hitmonchan", 107);
			this.a.put("Lickitung", 108);
			this.a.put("Koffing", 109);
			this.a.put("Weezing", 110);
			this.a.put("Rhyhorn", 111);
			this.a.put("Rhydon", 112);
			this.a.put("Chansey", 113);
			this.a.put("Tangela", 114);
			this.a.put("Kangaskhan", 115);
			this.a.put("Horsea", 116);
			this.a.put("Seadra", 117);
			this.a.put("Goldeen", 118);
			this.a.put("Seaking", 119);
			this.a.put("Staryu", 120);
			this.a.put("Starmie", 121);
			this.a.put("Mr. Mime", 122);
			this.a.put("Scyther", 123);
			this.a.put("Jynx", 124);
			this.a.put("Electrabuzz", 125);
			this.a.put("Magmar", 126);
			this.a.put("Pinsir", 127);
			this.a.put("Tauros", 128);
			this.a.put("Magikarp", 129);
			this.a.put("Gyarados", 130);
			this.a.put("Lapras", 131);
			this.a.put("Ditto", 132);
			this.a.put("Eevee", 133);
			this.a.put("Vaporeon", 134);
			this.a.put("Jolteon", 135);
			this.a.put("Flareon", 136);
			this.a.put("Porygon", 137);
			this.a.put("Omanyte", 138);
			this.a.put("Omastar", 139);
			this.a.put("Kabuto", 140);
			this.a.put("Kabutops", 141);
			this.a.put("Aerodactyl", 142);
			this.a.put("Snorlax", 143);
			this.a.put("Articuno", 144);
			this.a.put("Zapdos", 145);
			this.a.put("Moltres", 146);
			this.a.put("Dratini", 147);
			this.a.put("Dragonair", 148);
			this.a.put("Dragonite", 149);
			this.a.put("Mewtwo", 150);
			this.a.put("Mew", 151);
        }
		else if (dex == 1){
		//create dex b, listed by Pokdex Number
			this.b.put(0, "Honey Badger");
			this.b.put(1, "Bulbasaur");
			this.b.put(2, "Ivysaur");
			this.b.put(3, "Venusaur");
			this.b.put(4,"Charmander");
			this.b.put(5,"Charmeleon");
			this.b.put(6, "Charizard");
			this.b.put(7, "Squirtle");
			this.b.put(8, "Wartortle");
			this.b.put(9, "Blastoise");
			this.b.put(10, "Caterpie");
			this.b.put(11, "Metapod");
			this.b.put(12, "Butterfree");
			this.b.put(13, "Weedle");
			this.b.put(14, "Kakuna");
			this.b.put(15, "Beedrill");
			this.b.put(16, "Pidgey");
			this.b.put(17, "Pidgeotto");
			this.b.put(18, "Pidgeot");
			this.b.put(19, "Rattata");
			this.b.put(20, "Raticate");
			this.b.put(21, "Spearow");
			this.b.put(22, "Fearow");
			this.b.put(23, "Ekans");
			this.b.put(24, "Arbok");
			this.b.put(25, "Pikachu");
			this.b.put(26, "Raichu");
			this.b.put(27, "Sandshrew");
			this.b.put(28, "Sandslash");
			this.b.put(29, "Nidoran (Female)");
			this.b.put(30, "Nidorina");
			this.b.put(31, "Nidoqueen");
			this.b.put(32, "Nidoran (Male)");
			this.b.put(33, "Nidorino");
			this.b.put(34, "Nidoking");
			this.b.put(35, "Clefairy");
			this.b.put(36, "Clefable");
			this.b.put(37, "Vulpix");
			this.b.put(38, "Ninetales");
			this.b.put(39, "Jigglypuff");
			this.b.put(40, "Wigglytuff");
			this.b.put(41, "Zubat");
			this.b.put(42, "Golbat");
			this.b.put(43, "Oddish");
			this.b.put(44, "Gloom");
			this.b.put(45, "Vileplume");
			this.b.put(46, "Paras");
			this.b.put(47, "Parasect");
			this.b.put(48, "Venonat");
			this.b.put(49, "Venomoth");
			this.b.put(50, "Diglett");
			this.b.put(51, "Dugtrio");
			this.b.put(52, "Meowth");
			this.b.put(53, "Persian");
			this.b.put(54, "Psyduck");
			this.b.put(55, "Golduck");
			this.b.put(56, "Mankey");
			this.b.put(57, "Primeape");
			this.b.put(58, "Growlithe");
			this.b.put(59, "Arcanine");
			this.b.put(60, "Poliwag");
			this.b.put(61, "Poliwhirl");
			this.b.put(62, "Poliwrath");
			this.b.put(63, "Abra");
			this.b.put(64, "Kadabra");
			this.b.put(65, "Alakazam");
			this.b.put(66, "Machop");
			this.b.put(67, "Machoke");
			this.b.put(68, "Machamp");
			this.b.put(69, "Bellsprout");
			this.b.put(70, "Weepinbell");
			this.b.put(71, "Victreebell");
			this.b.put(72, "Tentacool");
			this.b.put(73, "Tentacruel");
			this.b.put(74, "Geodude");
			this.b.put(75, "Graveler");
			this.b.put(76, "Golem");
			this.b.put(77, "Ponyta");
			this.b.put(78, "Rapidash");
			this.b.put(79, "Slowpoke");
			this.b.put(80, "Slowbro");
			this.b.put(81, "Magnemite");
			this.b.put(82, "Magneton");
			this.b.put(83, "Farfetch'd");
			this.b.put(84, "Doduo");
			this.b.put(85, "Dodrio");
			this.b.put(86, "Seel");
			this.b.put(87, "Dewgong");
			this.b.put(88, "Grimer");
			this.b.put(89,  "Muk"); 
			this.b.put(90,"Shellder");
			this.b.put(91,"Cloyster");
			this.b.put(92, "Ghastly");
			this.b.put(93, "Haunter");
			this.b.put(94, "Gengar");
			this.b.put(95, "Onix");
			this.b.put(96, "Drowzee");
			this.b.put(97, "Hypno");
			this.b.put(98, "Krabby");
			this.b.put(99, "Kingler");
			this.b.put(100, "Voltorb");
			this.b.put(101, "Electrode");
			this.b.put(102, "Exeggcute");
			this.b.put(103, "Exeggcutor");
			this.b.put(104, "Cubone");
			this.b.put(105, "Marowak");
			this.b.put(106, "Hitmonlee");
			this.b.put(107, "Hitmonchan");
			this.b.put(108, "Lickitung");
			this.b.put(109, "Koffing");
			this.b.put(110, "Weezing");
			this.b.put(111, "Rhyhorn");
			this.b.put(112, "Rhydon");
			this.b.put(113, "Chansey");
			this.b.put(114, "Tangela");
			this.b.put(115, "Kangaskhan");
			this.b.put(116, "Horsea");
			this.b.put(117, "Seadra");
			this.b.put(118, "Goldeen");
			this.b.put(119, "Seaking");
			this.b.put(120, "Staryu");
			this.b.put(121, "Starmie");
			this.b.put(122, "Mr. Mime");
			this.b.put(123, "Scyther");
			this.b.put(124, "Jynx");
			this.b.put(125, "Electrabuzz");
			this.b.put(126, "Magmar");
			this.b.put(127, "Pinsir");
			this.b.put(128, "Tauros");
			this.b.put(129, "Magikarp");
			this.b.put(130, "Gyarados");
			this.b.put(131, "Lapras");
			this.b.put(132, "Ditto");
			this.b.put(133, "Eevee");
			this.b.put(134, "Vaporeon");
			this.b.put(135, "Jolteon");
			this.b.put(136, "Flareon");
			this.b.put(137, "Porygon");
			this.b.put(138, "Omanyte");
			this.b.put(139, "Omastar");
			this.b.put(140, "Kabuto");
			this.b.put(141, "Kabutops");
			this.b.put(142, "Aerodactyl");
			this.b.put(143, "Snorlax");
			this.b.put(144, "Articuno");
			this.b.put(145, "Zapdos");
			this.b.put(146, "Moltres");
			this.b.put(147, "Dratini");
			this.b.put(148, "Dragonair");
			this.b.put(149, "Dragonite");
			this.b.put(150, "Mewtwo");
			this.b.put(151, "Mew");
		}else{
			System.out.println("Error. No dex specified, no dex returned.");
		}
    }  //constructor
    
    // public HashMap getDex(int dex){  //return specified Pokedex
        // if (dex == 1) return this.a;
        // if (dex == 2) return this.b;
        // else return this.a;
	
	// }
	
	// public static void main(String[] args){
		// Dex dex = new Dex();
		// System.out.println(dex.b.get(1));
    // }
}